### ISSUE TITLE
Warum habt Ihr die XML-Daten gezippt abgelegt?

### ISSUE THREAD

**Issue by gitstief** [MKGHamburg/MKGCollectionOnlineLIDO_XML#4]
Das macht bei einem textbasierten System wie git nicht wirklich Sinn.

**Comment by steuke** [comment]
Moin @gitstief, 

gute Nachrichten: wir haben mit diesem Update wieder auf ungezipptes XML umgestellt.

Wer lieber ein Zip-Archiv haben möchte, kann das aktuelle Release als Archiv-Datei hier finden: 
- https://github.com/MKGHamburg/MKGCollectionOnlineLIDO_XML/releases

Viele Grüße, Stefan
